
include_directories(${CMAKE_HOME_DIRECTORY}/include)

AUX_SOURCE_DIRECTORY(example/clean_text GPT_SOVITS_CPP_TEST_CLEAN_TEXT_SOURCE)
add_executable(gpt_sovits_cpp_test_clean_text ${GPT_SOVITS_CPP_TEST_CLEAN_TEXT_SOURCE})
target_link_libraries(gpt_sovits_cpp_test_clean_text PUBLIC gsv_lib)


add_executable(gpt_sovits_cpp_test_bert example/model/bert.cpp)
target_link_libraries(gpt_sovits_cpp_test_bert PUBLIC gsv_lib)


add_executable(gpt_sovits_cpp_test_pipline_cpp example/pipline_cpp/gsv.cpp)
target_link_libraries(gpt_sovits_cpp_test_pipline_cpp PUBLIC gsv_lib)

# Streaming inference example
add_executable(gpt_sovits_cpp_streaming example/streaming/streaming_inference.cpp)
target_link_libraries(gpt_sovits_cpp_streaming PUBLIC gsv_lib)

# Distributed inference examples (legacy)
add_executable(gpt_sovits_cpp_cloud_create example/distributed/cloud_create_speaker.cpp)
target_link_libraries(gpt_sovits_cpp_cloud_create PUBLIC gsv_lib)

add_executable(gpt_sovits_cpp_edge_inference example/distributed/edge_inference.cpp)
target_link_libraries(gpt_sovits_cpp_edge_inference PUBLIC gsv_lib)

add_executable(gpt_sovits_cpp_multi_speaker example/distributed/multi_speaker.cpp)
target_link_libraries(gpt_sovits_cpp_multi_speaker PUBLIC gsv_lib)


if (WIN32 AND COMMAND auto_copy_backend_dlls)
  auto_copy_backend_dlls(gpt_sovits_cpp_test_clean_text)
  auto_copy_backend_dlls(gpt_sovits_cpp_test_bert)
  auto_copy_backend_dlls(gpt_sovits_cpp_test_pipline_cpp)
  auto_copy_backend_dlls(gpt_sovits_cpp_streaming)
  auto_copy_backend_dlls(gpt_sovits_cpp_cloud_create)
  auto_copy_backend_dlls(gpt_sovits_cpp_edge_inference)
  auto_copy_backend_dlls(gpt_sovits_cpp_multi_speaker)
endif()
